# -*- coding: utf-8 -*-
# @COPYRIGHT_begin
#
# Copyright [2016] Michał Szczygieł (m4gik), M4GiK Software
#
# @COPYRIGHT_end

#  connector, user, password, host, dbname


########## DATABASE CONFIGURATION
DATABASE_CONNECTOR = 'mysql+pymysql'
DATABASE_HOST = 'kamsbhp.linuxpl.info'
DATABASE_DATABASE_NAME = 'kamsbhp_sklep3'
DATABASE_USER = 'kamsbhp_kamserp'
DATABASE_PASSWORD = 'qetuo1357'
DATABASE_CHARSET = '?charset=utf8'
DOMAIN = 'http://kams.com.pl'
########## END DATABASE CONFIGURATION


########## ODOO DATABASE CONFIGURATION
ODOO_DATABASE_CONNECTOR = 'http'
ODOO_DATABASE_ADDRESS = '10.0.0.65'
ODOO_PORT = '8069'
ODOO_DATABASE_DATABASE_NAME = 'KamsERP'
ODOO_DATABASE_USER = 'kamsmichalszczygiel@gmail.com'
ODOO_DATABASE_PASSWORD = 'zuzia77'
########## END ODOO DATABASE CONFIGURATION


########## ODOO DATABASE CONFIGURATION
SUBIEKT_DATABASE_CONNECTOR = 'mssql+pyodbc'
SUBIEKT_DATABASE_ADDRESS = '10.0.0.54'
SUBIEKT_DATABASE_PORT = '1433'
SUBIEKT_DATABASE_DATABASE_NAME = 'KAMS'
SUBIEKT_DATABASE_USER = 'sa'
SUBIEKT_DATABASE_PASSWORD = ''
SUBIEKT_DATABASE_DRIVER = '?driver=ODBC+Driver+13+for+SQL+Server'
########## END ODOO DATABASE CONFIGURATION

########## KAMEERP CONFIGURATION
SALES_PERSON = 'bhpkams@gmail.com'

SHIPMENT_PREPAYMENT_NAME = 'Firma kurierska FedEx po wpłacie na konto'
SHIPMENT_PREPAYMENT_DESCRIPTION = 'Firma kurierska FedEx po wpłacie na konto'
SHIPMENT_PREPAYMENT_PRICE = float(14.00)
SHIPMENT_PREPAYMENT_COST = float(12.00)

SHIPMENT_PERSONAL_COLLECTION_NAME = 'Odbiór Osobisty'
SHIPMENT_PERSONAL_COLLECTION_DESCRIPTION = 'Odbiór Osobisty'
SHIPMENT_PERSONAL_COLLECTION_PRICE = float(0.00)
SHIPMENT_PERSONAL_COLLECTION_COST = float(0.00)

SHIPMENT_PAYMENT_ON_DELIVERY_NAME = 'Firma kurierska FedEx za pobraniem'
SHIPMENT_PAYMENT_ON_DELIVERY_DESCRIPTION = 'Firma kurierska FedEx za pobraniem'
SHIPMENT_PAYMENT_ON_DELIVERY_PRICE = float(14.99)
SHIPMENT_PAYMENT_ON_DELIVERY_COST = float(13.20)

SHIPMENT_INPOST_NAME = 'paczkomaty Inpost przedpłata'
SHIPMENT_INPOST_DESCRIPTION = 'paczkomaty Inpost przedpłata'
SHIPMENT_INPOST_PRICE = float(11.00)
SHIPMENT_INPOST_COST = float(8.60)
########## END KAMSERP CONFIGURATION